import unittest

from main import nucleotides


class DNASequenceTesting(unittest.TestCase):
    def setUp(self):
        pass


    def tearDown(self):
        pass


    def test_atcg_count(self):
        test_data = 'TGGTGCACCTTCGTCTGTATAACTATTTGTGGTAGCGTTAAGATGTGCACGGAGCTACTCTGACCACGTTTATACATTATCGGTAAAGTCCCCCCGTGACGCGAACAAAGTGATAGGGCGGCAGTATACAGTAACTATTTATTGGTCGTGGGTGGGACACCGGGATCGGTTATAGGAAATCTATGCTAAGTTAACGAGTCCCACATAAGCCGGAGATCGGCAGAGAGTTTTGACTGGCCCGCCCTTGCAGCTATGGAAGCCTTGCAGAGGGGCTGTCCGTTAAGTTGTCCGCAGTAGAAGGTCCGATTGCTTGGCGCAGGGGGGGCGCCATACGGTGACGGGCTGACCGGTGGGCGGTGCAGGCAGGCCCTCATTACGGTTTAGCGTGACTAGAGGACAATCAACAACCAATCGGTAAAATCTGTGTATCGGCCAGCGGTGATCGCTGATAATCAAAGAGAGGGGTGATAGGTAGTGTAATATTGGAATACATCTCATGGCAATGTCTGGACGGCCTATTTCGAAGTGTATTACGTTGTTCTTTTACAACGCGGCTCCAAGAAGCGTGGGAACAGTCGCACTCCCCTTGTCAGCTCACAGCTTTATACGTGATTGCTCTCTGCATCTGGGAATTGGCGAACTTCTGGAACTCTCATGCAGTGTGCATGACATTGGTACCGGCCACTGCCGAAATTTTCGACTAGGTTTTAAACGGGCCCGTTATTTTGGACTTACGCATTACGGGATTGTTCGGGCCCGACCCAGAGGTCCAGTGCGTGTTACAAGATGAACGAACAACCTGGCGACGTTGATATAAAGGGCATTGATTTCGTATTGCCGGCTGAGCTGACCGAACGTGGTTCTTCCTAGTGCCAGCGAATCATGCCCATCAGTCTGCAAAATGAATAGTGGCGCCTCATGCCAGTAGCATCGCTAGATCAGCAGGTGATCAAACGGGACTCTT'
        result = nucleotides.count_atcgs(test_data)
        print(result)


    def test_atcg_count_long(self):
        pass


if __name__ == "__main__":
    unittest.main()